// Code generated by 'freedom new-crud'
package object

import (
	"github.com/jinzhu/gorm"
	"time"
)

type Order struct {
	changes map[string]interface{}
	Id      int       `gorm:"primary_key;column:id"`
	UserId  int       `gorm:"column:user_id"`  // 用户id
	GoodsId int       `gorm:"column:goods_id"` // 商品id
	Num     int       `gorm:"column:num"`      // 数量
	Created time.Time `gorm:"column:created"`
	Updated time.Time `gorm:"column:updated"`
}

func (obj *Order) TableName() string {
	return "order"
}

// TakeChanges .
func (obj *Order) TakeChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// SetUserId .
func (obj *Order) SetUserId(userId int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.UserId = userId
	obj.changes["user_id"] = userId
}

// SetGoodsId .
func (obj *Order) SetGoodsId(goodsId int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.GoodsId = goodsId
	obj.changes["goods_id"] = goodsId
}

// SetNum .
func (obj *Order) SetNum(num int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Num = num
	obj.changes["num"] = num
}

// SetCreated .
func (obj *Order) SetCreated(created time.Time) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Created = created
	obj.changes["created"] = created
}

// SetUpdated .
func (obj *Order) SetUpdated(updated time.Time) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Updated = updated
	obj.changes["updated"] = updated
}

// AddUserId .
func (obj *Order) AddUserId(userId int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.UserId += userId
	obj.changes["user_id"] = gorm.Expr("user_id + ?", userId)
}

// AddGoodsId .
func (obj *Order) AddGoodsId(goodsId int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.GoodsId += goodsId
	obj.changes["goods_id"] = gorm.Expr("goods_id + ?", goodsId)
}

// AddNum .
func (obj *Order) AddNum(num int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Num += num
	obj.changes["num"] = gorm.Expr("num + ?", num)
}
