[consumer]
#开启 true
open = false
proxy_addr = "http://127.0.0.1:8000"
proxy_http2 = true

[producer]
#开启 true
open = false

[[producer_clients]]
servers = [":9092"]
#多实例name区分
#name = ""

[[consumer_clients]]
servers = [":9092"]
group_id = "freedom"

[other]