// Code generated by 'freedom new-project http2'
package repositorys

import "github.com/8treenet/freedom/example/http2/adapter/dto"

type GoodsInterface interface {
	GetGoods(goodsID int) dto.Goods
}
