// Code generated by 'freedom new-crud'
package object

import (
	"github.com/jinzhu/gorm"
	"time"
)

type OrderDetail struct {
	changes   map[string]interface{}
	Id        int       `gorm:"primary_key" column:"id"`
	OrderNo   string    `gorm:"column:order_no"`   // 订单id
	GoodsId   int       `gorm:"column:goods_id"`   // 商品id
	Num       int       `gorm:"column:num"`        // 数量
	GoodsName string    `gorm:"column:goods_name"` // 商品名称
	Created   time.Time `gorm:"column:created"`
	Updated   time.Time `gorm:"column:updated"`
}

func (obj *OrderDetail) TableName() string {
	return "order_detail"
}

// TakeChanges .
func (obj *OrderDetail) TakeChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// SetOrderNo .
func (obj *OrderDetail) SetOrderNo(orderNo string) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.OrderNo = orderNo
	obj.changes["order_no"] = orderNo
}

// SetGoodsId .
func (obj *OrderDetail) SetGoodsId(goodsId int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.GoodsId = goodsId
	obj.changes["goods_id"] = goodsId
}

// SetNum .
func (obj *OrderDetail) SetNum(num int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Num = num
	obj.changes["num"] = num
}

// SetGoodsName .
func (obj *OrderDetail) SetGoodsName(goodsName string) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.GoodsName = goodsName
	obj.changes["goods_name"] = goodsName
}

// SetCreated .
func (obj *OrderDetail) SetCreated(created time.Time) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Created = created
	obj.changes["created"] = created
}

// SetUpdated .
func (obj *OrderDetail) SetUpdated(updated time.Time) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Updated = updated
	obj.changes["updated"] = updated
}

// AddGoodsId .
func (obj *OrderDetail) AddGoodsId(goodsId int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.GoodsId += goodsId
	obj.changes["goods_id"] = gorm.Expr("goods_id + ?", goodsId)
}

// AddNum .
func (obj *OrderDetail) AddNum(num int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Num += num
	obj.changes["num"] = gorm.Expr("num + ?", num)
}
