// Code generated by 'freedom new-crud'
package object

import (
	"github.com/jinzhu/gorm"
	"time"
)

type User struct {
	changes  map[string]interface{}
	Id       int       `gorm:"primary_key" column:"id"` // 用户id
	Name     string    `gorm:"column:name"`             // 用户名称
	Money    int       `gorm:"column:money"`            // 金钱
	Password string    `gorm:"column:password"`         // 密码
	Created  time.Time `gorm:"column:created"`
	Updated  time.Time `gorm:"column:updated"`
}

func (obj *User) TableName() string {
	return "user"
}

// TakeChanges .
func (obj *User) TakeChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// SetName .
func (obj *User) SetName(name string) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Name = name
	obj.changes["name"] = name
}

// SetMoney .
func (obj *User) SetMoney(money int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Money = money
	obj.changes["money"] = money
}

// SetPassword .
func (obj *User) SetPassword(password string) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Password = password
	obj.changes["password"] = password
}

// SetCreated .
func (obj *User) SetCreated(created time.Time) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Created = created
	obj.changes["created"] = created
}

// SetUpdated .
func (obj *User) SetUpdated(updated time.Time) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Updated = updated
	obj.changes["updated"] = updated
}

// AddMoney .
func (obj *User) AddMoney(money int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Money += money
	obj.changes["money"] = gorm.Expr("money + ?", money)
}
