package project

func init() {
	content["/domain/po/po.go"] = objectsTemplate()
}

func objectsTemplate() string {
	return `
	//Package po generated by 'freedom new-project {{.PackagePath}}'
	package po
	`
}
