//Package dto code generated by 'freedom new-project infra-example'
package dto

// GoodsRep .
type GoodsRep struct {
	ID    int
	Name  string // 商品名称
	Price int    // 价格
	Stock int    // 库存
}

// OrderRep .
type OrderRep struct {
	ID        int    //订单ID
	GoodsID   int    // 商品ID
	GoodsName string // 商品名称
	Num       int    // 数量
	DateTime  string // 购买时间
}
