// Code generated by 'freedom new-crud'
package object

import (
	"github.com/jinzhu/gorm"
	"time"
)

type Delivery struct {
	changes        map[string]interface{}
	Id             int       `gorm:"primary_key;column:id"`
	AdminId        int       `gorm:"column:admin_id"`        // 管理员id
	OrderId        int       `gorm:"column:order_id"`        // 订单id
	TrackingNumber string    `gorm:"column:tracking_number"` // 快递单号
	Created        time.Time `gorm:"column:created"`
	Updated        time.Time `gorm:"column:updated"`
}

func (obj *Delivery) TableName() string {
	return "delivery"
}

// TakeChanges .
func (obj *Delivery) TakeChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// SetAdminId .
func (obj *Delivery) SetAdminId(adminId int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.AdminId = adminId
	obj.changes["admin_id"] = adminId
}

// SetOrderId .
func (obj *Delivery) SetOrderId(orderId int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.OrderId = orderId
	obj.changes["order_id"] = orderId
}

// SetTrackingNumber .
func (obj *Delivery) SetTrackingNumber(trackingNumber string) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.TrackingNumber = trackingNumber
	obj.changes["tracking_number"] = trackingNumber
}

// SetCreated .
func (obj *Delivery) SetCreated(created time.Time) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Created = created
	obj.changes["created"] = created
}

// SetUpdated .
func (obj *Delivery) SetUpdated(updated time.Time) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.Updated = updated
	obj.changes["updated"] = updated
}

// AddAdminId .
func (obj *Delivery) AddAdminId(adminId int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.AdminId += adminId
	obj.changes["admin_id"] = gorm.Expr("admin_id + ?", adminId)
}

// AddOrderId .
func (obj *Delivery) AddOrderId(orderId int) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.OrderId += orderId
	obj.changes["order_id"] = gorm.Expr("order_id + ?", orderId)
}
