// Code generated by 'freedom new-project base'
package repository

import (
	"github.com/8treenet/freedom"
)

func init() {
	freedom.Prepare(func(initiator freedom.Initiator) {
		initiator.BindRepository(func() *Default {
			return &Default{}
		})
	})
}

// Default .
type Default struct {
	freedom.Repository
}

// GetIP .
func (repo *Default) GetIP() string {
	//repo.DB().Find()
	repo.Worker.Logger().Infof("I'm Repository GetIP")
	return repo.Worker.IrisContext().RemoteAddr()
}

// GetUA - implement DefaultRepoInterface interface
func (repo *Default) GetUA() string {
	repo.Worker.Logger().Infof("I'm Repository GetUA")
	return repo.Worker.IrisContext().Request().UserAgent()
}
